# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/ConsoleGamesLib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/ConsoleGamesLib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/ConsoleGamesLib/CMakeFiles /workspaces/ConsoleGamesLib/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/ConsoleGamesLib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named strcap

# Build rule for target.
strcap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 strcap
.PHONY : strcap

# fast build rule for target.
strcap/fast:
	$(MAKE) -f CMakeFiles/strcap.dir/build.make CMakeFiles/strcap.dir/build
.PHONY : strcap/fast

#=============================================================================
# Target rules for targets named cs50

# Build rule for target.
cs50: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs50
.PHONY : cs50

# fast build rule for target.
cs50/fast:
	$(MAKE) -f CMakeFiles/cs50.dir/build.make CMakeFiles/cs50.dir/build
.PHONY : cs50/fast

#=============================================================================
# Target rules for targets named battleships

# Build rule for target.
battleships: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 battleships
.PHONY : battleships

# fast build rule for target.
battleships/fast:
	$(MAKE) -f CMakeFiles/battleships.dir/build.make CMakeFiles/battleships.dir/build
.PHONY : battleships/fast

#=============================================================================
# Target rules for targets named tictactoe

# Build rule for target.
tictactoe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tictactoe
.PHONY : tictactoe

# fast build rule for target.
tictactoe/fast:
	$(MAKE) -f CMakeFiles/tictactoe.dir/build.make CMakeFiles/tictactoe.dir/build
.PHONY : tictactoe/fast

#=============================================================================
# Target rules for targets named cgl

# Build rule for target.
cgl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cgl
.PHONY : cgl

# fast build rule for target.
cgl/fast:
	$(MAKE) -f CMakeFiles/cgl.dir/build.make CMakeFiles/cgl.dir/build
.PHONY : cgl/fast

games/battleships.o: games/battleships.c.o

.PHONY : games/battleships.o

# target to build an object file
games/battleships.c.o:
	$(MAKE) -f CMakeFiles/battleships.dir/build.make CMakeFiles/battleships.dir/games/battleships.c.o
.PHONY : games/battleships.c.o

games/battleships.i: games/battleships.c.i

.PHONY : games/battleships.i

# target to preprocess a source file
games/battleships.c.i:
	$(MAKE) -f CMakeFiles/battleships.dir/build.make CMakeFiles/battleships.dir/games/battleships.c.i
.PHONY : games/battleships.c.i

games/battleships.s: games/battleships.c.s

.PHONY : games/battleships.s

# target to generate assembly for a file
games/battleships.c.s:
	$(MAKE) -f CMakeFiles/battleships.dir/build.make CMakeFiles/battleships.dir/games/battleships.c.s
.PHONY : games/battleships.c.s

games/tictactoe.o: games/tictactoe.c.o

.PHONY : games/tictactoe.o

# target to build an object file
games/tictactoe.c.o:
	$(MAKE) -f CMakeFiles/tictactoe.dir/build.make CMakeFiles/tictactoe.dir/games/tictactoe.c.o
.PHONY : games/tictactoe.c.o

games/tictactoe.i: games/tictactoe.c.i

.PHONY : games/tictactoe.i

# target to preprocess a source file
games/tictactoe.c.i:
	$(MAKE) -f CMakeFiles/tictactoe.dir/build.make CMakeFiles/tictactoe.dir/games/tictactoe.c.i
.PHONY : games/tictactoe.c.i

games/tictactoe.s: games/tictactoe.c.s

.PHONY : games/tictactoe.s

# target to generate assembly for a file
games/tictactoe.c.s:
	$(MAKE) -f CMakeFiles/tictactoe.dir/build.make CMakeFiles/tictactoe.dir/games/tictactoe.c.s
.PHONY : games/tictactoe.c.s

libs/cs50.o: libs/cs50.c.o

.PHONY : libs/cs50.o

# target to build an object file
libs/cs50.c.o:
	$(MAKE) -f CMakeFiles/cs50.dir/build.make CMakeFiles/cs50.dir/libs/cs50.c.o
.PHONY : libs/cs50.c.o

libs/cs50.i: libs/cs50.c.i

.PHONY : libs/cs50.i

# target to preprocess a source file
libs/cs50.c.i:
	$(MAKE) -f CMakeFiles/cs50.dir/build.make CMakeFiles/cs50.dir/libs/cs50.c.i
.PHONY : libs/cs50.c.i

libs/cs50.s: libs/cs50.c.s

.PHONY : libs/cs50.s

# target to generate assembly for a file
libs/cs50.c.s:
	$(MAKE) -f CMakeFiles/cs50.dir/build.make CMakeFiles/cs50.dir/libs/cs50.c.s
.PHONY : libs/cs50.c.s

libs/strcap.o: libs/strcap.c.o

.PHONY : libs/strcap.o

# target to build an object file
libs/strcap.c.o:
	$(MAKE) -f CMakeFiles/strcap.dir/build.make CMakeFiles/strcap.dir/libs/strcap.c.o
.PHONY : libs/strcap.c.o

libs/strcap.i: libs/strcap.c.i

.PHONY : libs/strcap.i

# target to preprocess a source file
libs/strcap.c.i:
	$(MAKE) -f CMakeFiles/strcap.dir/build.make CMakeFiles/strcap.dir/libs/strcap.c.i
.PHONY : libs/strcap.c.i

libs/strcap.s: libs/strcap.c.s

.PHONY : libs/strcap.s

# target to generate assembly for a file
libs/strcap.c.s:
	$(MAKE) -f CMakeFiles/strcap.dir/build.make CMakeFiles/strcap.dir/libs/strcap.c.s
.PHONY : libs/strcap.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/cgl.dir/build.make CMakeFiles/cgl.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/cgl.dir/build.make CMakeFiles/cgl.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/cgl.dir/build.make CMakeFiles/cgl.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... strcap"
	@echo "... edit_cache"
	@echo "... cs50"
	@echo "... battleships"
	@echo "... tictactoe"
	@echo "... install/local"
	@echo "... cgl"
	@echo "... games/battleships.o"
	@echo "... games/battleships.i"
	@echo "... games/battleships.s"
	@echo "... games/tictactoe.o"
	@echo "... games/tictactoe.i"
	@echo "... games/tictactoe.s"
	@echo "... libs/cs50.o"
	@echo "... libs/cs50.i"
	@echo "... libs/cs50.s"
	@echo "... libs/strcap.o"
	@echo "... libs/strcap.i"
	@echo "... libs/strcap.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

